### ISSUE TITLE
indev branch: TypeError: this.api.oauth2.applications is not a function

### ISSUE THREAD

**Issue by pedall** [eslachance/komada-pieces#75]
```
2017-07-09 07:11:16 pm ERROR Uncaught Promise Error: 
 Promise {
  <rejected> TypeError: this.api.oauth2.applications is not a function
    at Komada.fetchApplication (C:\Users\Vlad\Desktop\Development\g4m3r-clan\node_modules\komada\node_modules\discord.js\src\client\Client.js:417:28)
    at Komada._ready (C:\Users\Vlad\Desktop\Development\g4m3r-clan\node_modules\komada\classes\client.js:105:55)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Komada.emit (events.js:207:7)
    at WebSocketConnection.triggerReady (C:\Users\Vlad\Desktop\Development\g4m3r-clan\node_modules\komada\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:123:17)
    at Promise.all.then (C:\Users\Vlad\Desktop\Development\g4m3r-clan\node_modules\komada\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:143:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7) } 
```

**Comment by kyranet** [comment]
Update Discord.js

**Comment by kyranet** [comment]
Sounds like somebody needs to update Discord.js, @CyberiumShadow 

Well... actually, if we update Discord.js, we'll have that error fixed (thanks Gus for forgetting that tiny but very important thing), but at the same time we'll have to change RichEmbed to MessageEmbed.

**Comment by pedall** [comment]
ah
